AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateTimelineFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: TimelineLite.Timeline::TimelineLite.Timeline::Create
       Runtime: dotnetcore2.0
       CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.zip
       Policies:
         -
           AmazonDynamoDBFullAccess
         -
           AWSXrayFullAccess
         -
           arn:aws:iam::346310877561:policy/SimpleDbFullAccess
       Timeout: 15
       MemorySize: 1024
       Tracing: Active
       Events:
         GetResource:
           Type: Api
           Properties:
             Path: /Timeline/Create
             Method: put
  EditTimelineTitleFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: TimelineLite.Timeline::TimelineLite.Timeline::EditTitle
       Runtime: dotnetcore2.0
       CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.zip
       Policies:
         -
           AmazonDynamoDBFullAccess
         -
           AWSXrayFullAccess
         -
           arn:aws:iam::346310877561:policy/SimpleDbFullAccess
       Timeout: 15
       MemorySize: 1024
       Tracing: Active
       Events:
         GetResource:
           Type: Api
           Properties:
             Path: /Timeline/Edit
             Method: put

  DeleteTimelineFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: TimelineLite.Timeline::TimelineLite.Timeline::Delete
       Runtime: dotnetcore2.0
       CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.zip
       Policies:
         -
           AmazonDynamoDBFullAccess
         -
           arn:aws:iam::346310877561:policy/SimpleDbFullAccess
       Timeout: 15
       MemorySize: 1024
       Tracing: Active
       Events:
         GetResource:
           Type: Api
           Properties:
             Path: /Timeline/Delete
             Method: put

  LinkEventToTimelineFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: TimelineLite.Timeline::TimelineLite.Timeline::LinkEvent
       Runtime: dotnetcore2.0
       CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.zip
       Policies:
         -
           AmazonDynamoDBFullAccess
         -
           AWSXrayFullAccess
         -
           arn:aws:iam::346310877561:policy/SimpleDbFullAccess
       Timeout: 15
       MemorySize: 1024
       Tracing: Active
       Events:
         GetResource:
           Type: Api
           Properties:
             Path: /Timeline/LinkEvent
             Method: put

  UnlinkEventFromTimelineFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: TimelineLite.Timeline::TimelineLite.Timeline::UnlinkEvent
       Runtime: dotnetcore2.0
       CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.zip
       Policies:
         -
           AmazonDynamoDBFullAccess
         -
           arn:aws:iam::346310877561:policy/SimpleDbFullAccess
         -
           AWSXrayFullAccess
       Timeout: 15
       MemorySize: 1024
       Tracing: Active
       Events:
         GetResource:
           Type: Api
           Properties:
             Path: /Timeline/UnlinkEvent
             Method: put

  GetTimelineFunction:
    Type: AWS::Serverless::Function
    Properties:
       Handler: TimelineLite.Timeline::TimelineLite.Timeline::Get
       Runtime: dotnetcore2.0
       CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.zip
       Policies:
         -
           AmazonDynamoDBFullAccess
         -
           arn:aws:iam::346310877561:policy/SimpleDbFullAccess
         -
           AWSXrayFullAccess
       Timeout: 15
       Tracing: Active
       MemorySize: 1024
       Events:
         GetResource:
           Type: Api
           Properties:
             Path: /Timeline/GetTimeline
             Method: get



    GetLinkedEvents:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite.TimelineEvent::TimelineLite.TimelineEvent::GetEvents
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.TimelineEvent.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
             -
               AWSXrayFullAccess
           Timeout: 15
           MemorySize: 1024
           Tracing: Active
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/GetEvents/
                 Method: get

    CreateTimelineEventFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite.TimelineEvent::TimelineLite.TimelineEvent::Create
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.TimelineEvent.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
             -
               AWSXrayFullAccess
           Timeout: 15
           MemorySize: 1024
           Tracing: Active
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEvent/Create
                 Method: put

    LinkTimelineEventsFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite.TimelineEvent::TimelineLite.TimelineEvent::LinkEvents
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.Timeline.TimelineEvent.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
             -
               AWSXrayFullAccess
           Timeout: 15
           MemorySize: 1024
           Tracing: Active
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEvent/LinkEvents
                 Method: put

    GetLinkedTimelineEventsFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite.TimelineEvent::TimelineLite.TimelineEvent::GetLinkedTimelineEvents
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
             -
               AWSXrayFullAccess
           Timeout: 15
           Tracing: Active
           MemorySize: 1024
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEvent/GetLinkedTimelineEvents
                 Method: get



    GenerateAttachmentPresignedUrl:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.TimelineEventAttachment::GeneratePresignedUrl
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
             -
               arn:aws:iam::aws:policy/AmazonS3FullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEventAttachment/GenerateAttachmentPresignedUrl
                 Method: get

    TimelineStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
            -
              AttributeName: TenantId
              AttributeType: S
        KeySchema:
            -
              AttributeName: TenantId
              KeyType: HASH
            -
              AttributeName: Id
              KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "TimelineStore"
