AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    CreateFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::Create
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/Create
                 Method: put
    EditTitleFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::EditTitle
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/Edit
                 Method: put
    DeleteFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::Delete
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess             
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/Delete
                 Method: put

    TimelineStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
            -
              AttributeName: TenantId
              AttributeType: S
        KeySchema:
            -
              AttributeName: TenantId
              KeyType: HASH
            -
              AttributeName: Id
              KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "TimelineStore"

    TimelineEventLinkStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
        KeySchema:
            -
              AttributeName: Id
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "TimelineEventLinkStore"

    EventStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
        KeySchema:
            -
              AttributeName: Id
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "TimelineEventsStore"

    EventAttachmentLinkStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
        KeySchema:
            -
              AttributeName: Id
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "EventAttachmentLinkStore"

    AttachmentStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
        KeySchema:
            -
              AttributeName: Id
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "AttachmentStore"
