AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    CreateTimelineFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::Create
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/Create
                 Method: put

    EditTimelineTitleFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::EditTitle
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/Edit
                 Method: put

    DeleteTimelineFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::Delete
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/Delete
                 Method: put

    LinkEventToTimelineFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::LinkEvent
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/LinkEvent
                 Method: put

    UnlinkEventFromTimelineFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::UnlinkEvent
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/UnlinkEvent
                 Method: put

    GetLinkedEvents:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::GetEvents
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/GetEvents/
                 Method: put

    CreateTimelineEventFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.TimelineEvent::Create
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEvent/Create
                 Method: put
    LinkTimelineEventsFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.TimelineEvent::LinkEvents
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEvent/LinkEvents
                 Method: put
    GetTimelineFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.Timeline::Get
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /Timeline/GetTimeline
                 Method: get

    GetLinkedTimelineEventsFunction:
        Type: AWS::Serverless::Function
        Properties:
           Handler: TimelineLite::TimelineLite.TimelineEvent::GetLinkedTimelineEvents
           Runtime: dotnetcore2.0
           CodeUri: s3://stewartw-test-bucket/TimelineLite.zip
           Policies:
             -
               AmazonDynamoDBFullAccess
             -
               arn:aws:iam::346310877561:policy/SimpleDbFullAccess
           Timeout: 15
           Events:
             GetResource:
               Type: Api
               Properties:
                 Path: /TimelineEvent/GetLinkedTimelineEvents
                 Method: get

    TimelineStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
            -
              AttributeName: TenantId
              AttributeType: S
        KeySchema:
            -
              AttributeName: TenantId
              KeyType: HASH
            -
              AttributeName: Id
              KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "TimelineStore"

    TimelineEventLinkStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
            -
              AttributeName: TenantId
              AttributeType: S
            -
              AttributeName: TimelineEventId
              AttributeType: S
        KeySchema:
            -
              AttributeName: TenantId
              KeyType: HASH
            -
              AttributeName: Id
              KeyType: RANGE

        GlobalSecondaryIndexes:
            -
                IndexName: TimelineEventId-Index
                KeySchema:
                    -
                        AttributeName: TimelineEventId
                        KeyType: HASH
                Projection:
                    ProjectionType: ALL
                ProvisionedThroughput:
                    ReadCapacityUnits: 5
                    WriteCapacityUnits: 5

        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

        TableName: "TimelineEventLinkStore"
    EventStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
            -
              AttributeName: TenantId
              AttributeType: S
        KeySchema:
            -
              AttributeName: TenantId
              KeyType: HASH
            -
              AttributeName: Id
              KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "TimelineEventStore"

    EventAttachmentLinkStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
        KeySchema:
            -
              AttributeName: Id
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "EventAttachmentLinkStore"

    AttachmentStorage:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
            -
              AttributeName: Id
              AttributeType: S
        KeySchema:
            -
              AttributeName: Id
              KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: "AttachmentStore"
